security:
    encoders:
        App\Domain\User\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Domain\User\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Core\Auth\Login\LoginAuthenticator
            user_checker: App\Core\Auth\UserChecker
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }          # login page
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # registration page
        - { path: ^/, roles: ROLE_USER }                              # all other - requires authentication
